# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mkornfield/dev/gambit

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mkornfield/repo/gambit

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mkornfield/repo/gambit/CMakeFiles /Users/mkornfield/repo/gambit//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mkornfield/repo/gambit/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Server

# Build rule for target.
Server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Server
.PHONY : Server

# fast build rule for target.
Server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/build
.PHONY : Server/fast

#=============================================================================
# Target rules for targets named Client

# Build rule for target.
Client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Client
.PHONY : Client

# fast build rule for target.
Client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/build
.PHONY : Client/fast

#=============================================================================
# Target rules for targets named Tests

# Build rule for target.
Tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tests
.PHONY : Tests

# fast build rule for target.
Tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/build
.PHONY : Tests/fast

src/ClientPrediction.o: src/ClientPrediction.cpp.o
.PHONY : src/ClientPrediction.o

# target to build an object file
src/ClientPrediction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/ClientPrediction.cpp.o
.PHONY : src/ClientPrediction.cpp.o

src/ClientPrediction.i: src/ClientPrediction.cpp.i
.PHONY : src/ClientPrediction.i

# target to preprocess a source file
src/ClientPrediction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/ClientPrediction.cpp.i
.PHONY : src/ClientPrediction.cpp.i

src/ClientPrediction.s: src/ClientPrediction.cpp.s
.PHONY : src/ClientPrediction.s

# target to generate assembly for a file
src/ClientPrediction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/ClientPrediction.cpp.s
.PHONY : src/ClientPrediction.cpp.s

src/FileSystem.o: src/FileSystem.cpp.o
.PHONY : src/FileSystem.o

# target to build an object file
src/FileSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/FileSystem.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/FileSystem.cpp.o
.PHONY : src/FileSystem.cpp.o

src/FileSystem.i: src/FileSystem.cpp.i
.PHONY : src/FileSystem.i

# target to preprocess a source file
src/FileSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/FileSystem.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/FileSystem.cpp.i
.PHONY : src/FileSystem.cpp.i

src/FileSystem.s: src/FileSystem.cpp.s
.PHONY : src/FileSystem.s

# target to generate assembly for a file
src/FileSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/FileSystem.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/FileSystem.cpp.s
.PHONY : src/FileSystem.cpp.s

src/GameLoop.o: src/GameLoop.cpp.o
.PHONY : src/GameLoop.o

# target to build an object file
src/GameLoop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/GameLoop.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/GameLoop.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/GameLoop.cpp.o
.PHONY : src/GameLoop.cpp.o

src/GameLoop.i: src/GameLoop.cpp.i
.PHONY : src/GameLoop.i

# target to preprocess a source file
src/GameLoop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/GameLoop.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/GameLoop.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/GameLoop.cpp.i
.PHONY : src/GameLoop.cpp.i

src/GameLoop.s: src/GameLoop.cpp.s
.PHONY : src/GameLoop.s

# target to generate assembly for a file
src/GameLoop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/GameLoop.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/GameLoop.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/GameLoop.cpp.s
.PHONY : src/GameLoop.cpp.s

src/InputSystem.o: src/InputSystem.cpp.o
.PHONY : src/InputSystem.o

# target to build an object file
src/InputSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/InputSystem.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/InputSystem.cpp.o
.PHONY : src/InputSystem.cpp.o

src/InputSystem.i: src/InputSystem.cpp.i
.PHONY : src/InputSystem.i

# target to preprocess a source file
src/InputSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/InputSystem.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/InputSystem.cpp.i
.PHONY : src/InputSystem.cpp.i

src/InputSystem.s: src/InputSystem.cpp.s
.PHONY : src/InputSystem.s

# target to generate assembly for a file
src/InputSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/InputSystem.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/InputSystem.cpp.s
.PHONY : src/InputSystem.cpp.s

src/Logger.o: src/Logger.cpp.o
.PHONY : src/Logger.o

# target to build an object file
src/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Logger.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/Logger.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/Logger.cpp.o
.PHONY : src/Logger.cpp.o

src/Logger.i: src/Logger.cpp.i
.PHONY : src/Logger.i

# target to preprocess a source file
src/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Logger.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/Logger.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/Logger.cpp.i
.PHONY : src/Logger.cpp.i

src/Logger.s: src/Logger.cpp.s
.PHONY : src/Logger.s

# target to generate assembly for a file
src/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Logger.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/Logger.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/Logger.cpp.s
.PHONY : src/Logger.cpp.s

src/NetworkClient.o: src/NetworkClient.cpp.o
.PHONY : src/NetworkClient.o

# target to build an object file
src/NetworkClient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/NetworkClient.cpp.o
.PHONY : src/NetworkClient.cpp.o

src/NetworkClient.i: src/NetworkClient.cpp.i
.PHONY : src/NetworkClient.i

# target to preprocess a source file
src/NetworkClient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/NetworkClient.cpp.i
.PHONY : src/NetworkClient.cpp.i

src/NetworkClient.s: src/NetworkClient.cpp.s
.PHONY : src/NetworkClient.s

# target to generate assembly for a file
src/NetworkClient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/NetworkClient.cpp.s
.PHONY : src/NetworkClient.cpp.s

src/NetworkProtocol.o: src/NetworkProtocol.cpp.o
.PHONY : src/NetworkProtocol.o

# target to build an object file
src/NetworkProtocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/NetworkProtocol.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/NetworkProtocol.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/NetworkProtocol.cpp.o
.PHONY : src/NetworkProtocol.cpp.o

src/NetworkProtocol.i: src/NetworkProtocol.cpp.i
.PHONY : src/NetworkProtocol.i

# target to preprocess a source file
src/NetworkProtocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/NetworkProtocol.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/NetworkProtocol.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/NetworkProtocol.cpp.i
.PHONY : src/NetworkProtocol.cpp.i

src/NetworkProtocol.s: src/NetworkProtocol.cpp.s
.PHONY : src/NetworkProtocol.s

# target to generate assembly for a file
src/NetworkProtocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/NetworkProtocol.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/NetworkProtocol.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/NetworkProtocol.cpp.s
.PHONY : src/NetworkProtocol.cpp.s

src/NetworkServer.o: src/NetworkServer.cpp.o
.PHONY : src/NetworkServer.o

# target to build an object file
src/NetworkServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/NetworkServer.cpp.o
.PHONY : src/NetworkServer.cpp.o

src/NetworkServer.i: src/NetworkServer.cpp.i
.PHONY : src/NetworkServer.i

# target to preprocess a source file
src/NetworkServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/NetworkServer.cpp.i
.PHONY : src/NetworkServer.cpp.i

src/NetworkServer.s: src/NetworkServer.cpp.s
.PHONY : src/NetworkServer.s

# target to generate assembly for a file
src/NetworkServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/NetworkServer.cpp.s
.PHONY : src/NetworkServer.cpp.s

src/RemotePlayerInterpolation.o: src/RemotePlayerInterpolation.cpp.o
.PHONY : src/RemotePlayerInterpolation.o

# target to build an object file
src/RemotePlayerInterpolation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/RemotePlayerInterpolation.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/RemotePlayerInterpolation.cpp.o
.PHONY : src/RemotePlayerInterpolation.cpp.o

src/RemotePlayerInterpolation.i: src/RemotePlayerInterpolation.cpp.i
.PHONY : src/RemotePlayerInterpolation.i

# target to preprocess a source file
src/RemotePlayerInterpolation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/RemotePlayerInterpolation.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/RemotePlayerInterpolation.cpp.i
.PHONY : src/RemotePlayerInterpolation.cpp.i

src/RemotePlayerInterpolation.s: src/RemotePlayerInterpolation.cpp.s
.PHONY : src/RemotePlayerInterpolation.s

# target to generate assembly for a file
src/RemotePlayerInterpolation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/RemotePlayerInterpolation.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/RemotePlayerInterpolation.cpp.s
.PHONY : src/RemotePlayerInterpolation.cpp.s

src/ServerGameState.o: src/ServerGameState.cpp.o
.PHONY : src/ServerGameState.o

# target to build an object file
src/ServerGameState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/ServerGameState.cpp.o
.PHONY : src/ServerGameState.cpp.o

src/ServerGameState.i: src/ServerGameState.cpp.i
.PHONY : src/ServerGameState.i

# target to preprocess a source file
src/ServerGameState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/ServerGameState.cpp.i
.PHONY : src/ServerGameState.cpp.i

src/ServerGameState.s: src/ServerGameState.cpp.s
.PHONY : src/ServerGameState.s

# target to generate assembly for a file
src/ServerGameState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/ServerGameState.cpp.s
.PHONY : src/ServerGameState.cpp.s

src/Window.o: src/Window.cpp.o
.PHONY : src/Window.o

# target to build an object file
src/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/Window.cpp.o
.PHONY : src/Window.cpp.o

src/Window.i: src/Window.cpp.i
.PHONY : src/Window.i

# target to preprocess a source file
src/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/Window.cpp.i
.PHONY : src/Window.cpp.i

src/Window.s: src/Window.cpp.s
.PHONY : src/Window.s

# target to generate assembly for a file
src/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/Window.cpp.s
.PHONY : src/Window.cpp.s

src/client_main.o: src/client_main.cpp.o
.PHONY : src/client_main.o

# target to build an object file
src/client_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/client_main.cpp.o
.PHONY : src/client_main.cpp.o

src/client_main.i: src/client_main.cpp.i
.PHONY : src/client_main.i

# target to preprocess a source file
src/client_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/client_main.cpp.i
.PHONY : src/client_main.cpp.i

src/client_main.s: src/client_main.cpp.s
.PHONY : src/client_main.s

# target to generate assembly for a file
src/client_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/src/client_main.cpp.s
.PHONY : src/client_main.cpp.s

src/server_main.o: src/server_main.cpp.o
.PHONY : src/server_main.o

# target to build an object file
src/server_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server_main.cpp.o
.PHONY : src/server_main.cpp.o

src/server_main.i: src/server_main.cpp.i
.PHONY : src/server_main.i

# target to preprocess a source file
src/server_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server_main.cpp.i
.PHONY : src/server_main.cpp.i

src/server_main.s: src/server_main.cpp.s
.PHONY : src/server_main.s

# target to generate assembly for a file
src/server_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/server_main.cpp.s
.PHONY : src/server_main.cpp.s

src/test_main.o: src/test_main.cpp.o
.PHONY : src/test_main.o

# target to build an object file
src/test_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/test_main.cpp.o
.PHONY : src/test_main.cpp.o

src/test_main.i: src/test_main.cpp.i
.PHONY : src/test_main.i

# target to preprocess a source file
src/test_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/test_main.cpp.i
.PHONY : src/test_main.cpp.i

src/test_main.s: src/test_main.cpp.s
.PHONY : src/test_main.s

# target to generate assembly for a file
src/test_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tests.dir/build.make CMakeFiles/Tests.dir/src/test_main.cpp.s
.PHONY : src/test_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Client"
	@echo "... Server"
	@echo "... Tests"
	@echo "... src/ClientPrediction.o"
	@echo "... src/ClientPrediction.i"
	@echo "... src/ClientPrediction.s"
	@echo "... src/FileSystem.o"
	@echo "... src/FileSystem.i"
	@echo "... src/FileSystem.s"
	@echo "... src/GameLoop.o"
	@echo "... src/GameLoop.i"
	@echo "... src/GameLoop.s"
	@echo "... src/InputSystem.o"
	@echo "... src/InputSystem.i"
	@echo "... src/InputSystem.s"
	@echo "... src/Logger.o"
	@echo "... src/Logger.i"
	@echo "... src/Logger.s"
	@echo "... src/NetworkClient.o"
	@echo "... src/NetworkClient.i"
	@echo "... src/NetworkClient.s"
	@echo "... src/NetworkProtocol.o"
	@echo "... src/NetworkProtocol.i"
	@echo "... src/NetworkProtocol.s"
	@echo "... src/NetworkServer.o"
	@echo "... src/NetworkServer.i"
	@echo "... src/NetworkServer.s"
	@echo "... src/RemotePlayerInterpolation.o"
	@echo "... src/RemotePlayerInterpolation.i"
	@echo "... src/RemotePlayerInterpolation.s"
	@echo "... src/ServerGameState.o"
	@echo "... src/ServerGameState.i"
	@echo "... src/ServerGameState.s"
	@echo "... src/Window.o"
	@echo "... src/Window.i"
	@echo "... src/Window.s"
	@echo "... src/client_main.o"
	@echo "... src/client_main.i"
	@echo "... src/client_main.s"
	@echo "... src/server_main.o"
	@echo "... src/server_main.i"
	@echo "... src/server_main.s"
	@echo "... src/test_main.o"
	@echo "... src/test_main.i"
	@echo "... src/test_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

